#!/bin/sh

URED="\e[4;31m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
LGRAY="\e[37m"
LRED="\e[91m"
LGREEN="\e[92m"
LYELLOW="\e[93m"
LBLUE="\e[94m"
LMAGENTA="\e[95m"
LCYAN="\e[96m"
WHITE="\e[97m"
ENDCOLOR="\e[0m"

echo "${URED}"`hostnamectl | grep "Operating System" | cut -d ' ' -f5-`" :: Kernel "`uname -r`"${ENDCOLOR}"
echo "\e[1;33m"`awk -F':' '/^model name/ {print $2}' /proc/cpuinfo | uniq | sed -e 's/^[ \t]*//'`
echo `cat /sys/devices/virtual/dmi/id/board_name`" ("`cat /sys/class/dmi/id/sys_vendor`")\e[0m"
echo "\e[1;96mCPU USAGE: "`cat /proc/stat | awk '/cpu/{printf("%.2f%\n"), ($2+$4)*100/($2+$4+$5)}' |  awk '{print $0}' | head -1`" | RAM USAGE: "`free | awk '/Mem/{printf("%.2f%"), $3/$2*100}'`"\e[0m "
echo "\e[1;34mDesktop Info:\tXXX\e[0m"
echo ""
echo "${RED}${ENDCOLOR} ${LRED}${ENDCOLOR} ${GREEN}${ENDCOLOR} ${LGREEN}${ENDCOLOR} ${YELLOW}${ENDCOLOR} ${LYELLOW}${ENDCOLOR} ${BLUE}${ENDCOLOR} ${LBLUE}${ENDCOLOR} ${MAGENTA}${ENDCOLOR} ${LMAGENTA}${ENDCOLOR} ${CYAN}${ENDCOLOR} ${LCYAN}${ENDCOLOR} ${LGRAY}${ENDCOLOR} ${WHITE}${ENDCOLOR}"
#echo "\e[1;31m\e[0m\e[1;91m\e[0m \e[1;32m\e[0m\e[1;92m\e[0m \e[1;33m\e[0m\e[1;93m\e[0m \e[1;34m\e[0m\e[1;94m\e[0m \e[1;35m\e[0m\e[1;95m\e[0m \e[1;36m\e[0m\e[1;96m\e[0m \e[1;37m\e[0m\e[1;97m\e[0m"
echo ""
echo ""
