#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DisplayPort-0 --mode 1920x1080 --pos 2560x0 --rotate right --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --primary --mode 2560x1080 --pos 0x148 --rotate normal --output DVI-D-0 --off
killall "dunst"
/usr/bin/dunst &
#setxkbmap latam &
killall "nitrogen"
nitrogen --set-zoom-fill --random $HOME/Pictures/Backgrounds/ &
xdg-screensaver suspend 0x6c7 &
picom -b --backend glx &
xsetroot -cursor_name left_ptr &
killall conky
conky -b &
#~/.config/conky/scripts/blur-conky.sh

bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DisplayPort-0 -d 0

bsp-layout set even 0 &
bsp-layout set tall 1 -- --master-size 0.57 &
bsp-layout set tall 2 -- --master-size 0.57 &
bsp-layout set even 3 &
bsp-layout set even 4 &
bsp-layout set even 5 &
bsp-layout set even 8 &
bsp-layout set even 9 &

# Default Theme
bspc config normal_border_color "#2a2a2a"
bspc config active_border_color "#2a2a2a"
bspc config focused_border_color "#eaeaea"
bspc config presel_feedback_color "#2a2a2a"

# Gruvbox theme
#bspc config focused_border_color "#fe8019"

# Dracula theme
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"
# Dracula cyan border:
#bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#8be9fd"

# Nordic border:
#bspc config active_border_color "#4c566a"
#bspc config focused_border_color "#88c0d0"

bspc config border_width          2
bspc config window_gap            10
bspc config split_ratio           0.57
bspc config click_to_focus        true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a gimp desktop=^9 follow=on
bspc rule -a Filezilla desktop=^4 follow=on
bspc rule -a Galculator state=floating
bspc rule -a Conky state=floating layer=below flag=sticky border=off
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
