#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

killall "picom"
picom -CGb --backend glx &
killall "nitrogen"
nitrogen --set-zoom-fill --random $HOME/Pictures/Backgrounds/ &
$HOME/.config/polybar/launch.sh &
xdg-screensaver suspend 0x6b1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color "#fe8019"
bspc config border_width          3
bspc config window_gap            15
bspc config split_ratio           0.50
bspc config click_to_focus        true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
